variables:
  system.debug: true

pool:
  vmImage: 'ubuntu-latest'

name: $(rev:r)

steps:

# - task: Docker@0
#   displayName: 'Build JAR File with SBT'
#   inputs:
#     containerregistrytype: 'Container Registry'
#     action: 'Run an image'
#     imageName: 'bigtruedata/sbt:0.13.15-2.12.2'
#     qualifyImageName: false
#     containerName: sbt
#     volumes: '$(Build.Repository.LocalPath):/app'
#     containerCommand: 'sbt "set test in Test := {}" clean assembly'
#     detached: false

- task: Gradle@2
  displayName: 'Build JAR File with Gradle'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'sourcesJar' # build -x test
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish JAR file to Artifacts'
  inputs:
    PathtoPublish: '$(Build.Repository.LocalPath)/build/libs'
    ArtifactName: 'jar-file'
    # https://dev.azure.com/mojio/_apis/resources/Containers/3433820/jar-file?itemPath=jar-file%2Fcouchbase-spark-connector_2.11-2.3.0.jar
- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'Analytics'

- task: AzureCLI@2
  displayName: 'Publish JAR file to Repo'
  inputs:
    azureSubscription: 'BizSpark Development (RM)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      # mvn deploy:deploy-file "-Durl=$(githubPackagesUrl)" "-DrepositoryId=Analytics" "-Dfile=$(Build.Repository.LocalPath)/build/libs/couchbase-spark-connector_2.11-2.3.0.jar" "-Dtoken=$(githubPackagesPassword)" "-DgeneratePom=true" "-DgeneratePom.description=couchbase" "-Dpackaging=jar" "-Dversion=2.3.0-MOJIO-$(Build.BuildNumber)" "-DgroupId=com.couchbase.client" "-DartifactId=spark-connector"
      mvn deploy:deploy-file "-Durl=$(azDevOpsArtifactsUrl)" "-DrepositoryId=Analytics" "-Dfile=$(Build.Repository.LocalPath)/build/libs/couchbase-spark-connector_2.11-2.3.0.jar" "-Dtoken=$(azDevOpsArtifactsPassword)" "-DgeneratePom=true" "-DgeneratePom.description=couchbase" "-Dpackaging=jar" "-Dversion=2.3.0-MOJIO-$(Build.BuildNumber)" "-DgroupId=com.couchbase.client" "-DartifactId=spark-connector"
