variables:
  system.debug: true

pool:
  vmImage: 'ubuntu-latest'

name: $(rev:r)

steps:

# - task: Docker@0
#   displayName: 'Build JAR File with SBT'
#   inputs:
#     containerregistrytype: 'Container Registry'
#     action: 'Run an image'
#     imageName: 'bigtruedata/sbt:0.13.15-2.12.2'
#     qualifyImageName: false
#     containerName: sbt
#     volumes: '$(Build.Repository.LocalPath):/app'
#     containerCommand: 'sbt "set test in Test := {}" clean assembly'
#     detached: false

- task: Gradle@2
  displayName: 'Build JAR File with Gradle'
  inputs:
    gradleWrapperFile: 'gradlew'
    # tasks: 'build -x test'
    tasks: 'publishToMavenLocal --debug'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: Gradle@2
  displayName: 'Build POM File with Gradle'
  inputs:
    gradleWrapperFile: 'gradlew'
    tasks: 'generatePomFileForMavenJavaPublication --debug'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false

- task: PublishBuildArtifacts@1
  displayName: 'Publish JAR file to Artifacts'
  inputs:
    # PathtoPublish: '~/.m2/repository/com/couchbase/client/spark-connector_2.11/2.3.1-MOJIO'
    PathtoPublish: '$(Build.Repository.LocalPath)/build'
    ArtifactName: 'jar-file'

- task: MavenAuthenticate@0
  inputs:
    artifactsFeeds: 'Analytics'

- task: AzureCLI@2
  displayName: 'Publish JAR file to Repo'
  inputs:
    azureSubscription: 'BizSpark Development (RM)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      mvn deploy:deploy-file "-Durl=$(azDevOpsArtifactsUrl)" "-DrepositoryId=Analytics" "-Dfile=$(Build.Repository.LocalPath)/build/libs/couchbase-spark-connector_2.11-2.3.1-MOJIO.jar" "-Dtoken=$(azDevOpsArtifactsPassword)" "-DgeneratePom=true" "-DgeneratePom.description=couchbase" "-Dpackaging=jar" "-Dversion=2.3.1-MOJIO-$(Build.BuildNumber)" "-DgroupId=com.couchbase.client" "-DartifactId=spark-connector"
      # mvn deploy:deploy-file "-Durl=$(azDevOpsArtifactsUrl)" "-DrepositoryId=Analytics" "-Dfile=$(Build.Repository.LocalPath)/build/libs/couchbase-spark-connector_2.11-2.3.1-MOJIO.jar" "-Dtoken=$(azDevOpsArtifactsPassword)" "-DgeneratePom=false" "-DpomFile=$(Build.Repository.LocalPath)/build/libs/couchbase-spark-connector_2.11-2.3.1-MOJIO.pom" "-Dpackaging=jar" "-Dversion=2.3.1-MOJIO-$(Build.BuildNumber)" "-DgroupId=com.couchbase.client" "-DartifactId=spark-connector"
